def my_function(fname):
  print(fname + " Raad")
print("My family is compsed from my wife Azraa El jawhari and the following children:")
my_function("Batoul")
my_function("Ali")
my_function("Haidar")
my_function("Nour")
print("Thank my god")
print("All time Thank my god")
print("With pleasure we say Thank my god")
